// Embeds the built client (dist/client) into the Worker bundle so `wrangler deploy`
// needs no separate asset upload. Also writes wrangler.deploy.json without the
// `assets` block, which is only used by the Vite dev server.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, extname } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const dist = join(root, "dist/client");
const types = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".json": "application/json",
  ".txt": "text/plain; charset=utf-8",
  ".woff2": "font/woff2",
};

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (!name.startsWith(".")) out.push(p);
  }
  return out;
}

const files = {};
for (const file of walk(dist)) {
  const path = "/" + relative(dist, file).split("\\").join("/");
  files[path] = { type: types[extname(file)] ?? "application/octet-stream", data: readFileSync(file).toString("base64") };
}
const size = Object.values(files).reduce((n, f) => n + f.data.length, 0);
writeFileSync(
  join(root, "server/generated/assets.ts"),
  `// Generated by scripts/embed-assets.mjs. Do not edit.\nexport const ASSETS: Record<string, { type: string; data: string }> = ${JSON.stringify(files)};\n`,
);

const jsonc = readFileSync(join(root, "wrangler.jsonc"), "utf8")
  .replace(/^\s*\/\/.*$/gm, "")
  .replace(/,(\s*[}\]])/g, "$1");
const cfg = JSON.parse(jsonc);
delete cfg.assets;
delete cfg.$schema;
writeFileSync(join(root, "wrangler.deploy.json"), JSON.stringify(cfg, null, 2) + "\n");
console.log(`[embed] ${Object.keys(files).length} files, ${(size / 1024).toFixed(0)} KB base64 -> server/generated/assets.ts`);
